INF QcomPkg/XBLCore/XBLCore.inf

FILE FREEFORM = DDE58710-41CD-4306-DBFB-3FA90BB1D2DD {
    SECTION UI = "uefiplat.cfg"
    SECTION RAW = RawFiles/uefiplat.cfg
}

INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF QcomPkg/Drivers/TzDxe/ScmDxe.inf
INF QcomPkg/Drivers/SecurityDxe/SecurityDxe.inf
INF QcomPkg/Drivers/MorPpiDxe/MorPpiDxe.inf
INF QcomPkg/Drivers/TzDxe/TzDxe.inf
INF QcomPkg/Drivers/MeasureBootDxe/MeasureBootDxe.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF QcomPkg/Drivers/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/ReportStatusCodeRouterRuntimeDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/StatusCodeHandlerRuntimeDxe.inf
INF QcomPkg/Drivers/VariableDxe/WP/VariableDxe.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF QcomPkg/Drivers/FontDxe/FontDxe.inf
INF QcomPkg/Drivers/SmbiosDxe/SmbiosDxe.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxe.inf
INF QcomPkg/Drivers/SmBiosTableDxe/SmBiosTableDxe.inf
INF MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableDxe.inf
INF QcomPkg/Drivers/AcpiPlatformDxe/AcpiPlatformDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF QcomPkg/Drivers/OSConfigDxe/OSConfigDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF QcomPkg/Drivers/CmdDbDxe/CmdDbDxe.inf
INF QcomPkg/Drivers/RpmhDxe/RpmhDxe.inf
INF QcomPkg/Drivers/CPRDxe/CPRDxe.inf
INF QcomPkg/Drivers/PdcDxe/PdcDxe.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/I2CKeyboard/I2CKeyboard.inf
INF QcomPkg/Drivers/SPIDxe/SPIDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/CrashDumpDxe/CrashDumpDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe.inf
INF QcomPkg/Drivers/UFSDxe/UFSDxe.inf
INF QcomPkg/Drivers/RawFileSystemDxe/RawFileSystemDxe.inf
INF MdeModulePkg/Universal/Acpi/FirmwarePerformanceDataTableDxe/FirmwarePerformanceDxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeWp.inf
INF QcomPkg/Drivers/ChargerExDxe/NullLib/ChargerExDxeNull.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
INF QcomPkg/Drivers/AdcDxe/AdcDxe.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/LimitsDxe/LimitsDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF MdeModulePkg/Universal/Network/SnpDxe/SnpDxe.inf
INF MdeModulePkg/Universal/Network/DpcDxe/DpcDxe.inf
INF MdeModulePkg/Universal/Network/ArpDxe/ArpDxe.inf
INF MdeModulePkg/Universal/Network/Dhcp4Dxe/Dhcp4Dxe.inf
INF MdeModulePkg/Universal/Network/Ip4Dxe/Ip4Dxe.inf
INF MdeModulePkg/Universal/Network/MnpDxe/MnpDxe.inf
INF MdeModulePkg/Universal/Network/VlanConfigDxe/VlanConfigDxe.inf
INF MdeModulePkg/Universal/Network/Mtftp4Dxe/Mtftp4Dxe.inf
INF NetworkPkg/TcpDxe/TcpDxe.inf
INF MdeModulePkg/Universal/Network/Udp4Dxe/Udp4Dxe.inf
INF NetworkPkg/UefiPxeBcDxe/UefiPxeBcDxe.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/XhciPciEmulationDxe/XhciPciEmulationDxe.inf
INF QcomPkg/Drivers/XhciDxe/XhciDxe.inf
INF QcomPkg/Drivers/UsbBusDxe/UsbBusDxe.inf
INF QcomPkg/Drivers/UsbKbDxe/UsbKbDxe.inf
INF QcomPkg/Drivers/UsbMassStorageDxe/UsbMassStorageDxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/UsbInitDxe/UsbInitDxe.inf
INF QcomPkg/Drivers/UsbfnChgDxe/UsbfnChgDxe.inf
INF OptionRomPkg/Bus/Usb/UsbNetworking/Ax88772b/Ax88772b.inf
INF MdeModulePkg/Universal/Acpi/BootGraphicsResourceTableDxe/BootGraphicsResourceTableDxe.inf
INF MdeModulePkg/Bus/Pci/PciBusDxe/PciBusDxe.inf
INF QcomPkg/Drivers/HashDxe/HashDxe.inf
INF QcomPkg/Drivers/CipherDxe/CipherDxe.inf
INF QcomPkg/Drivers/RNGDxe/RngDxe.inf
INF QcomPkg/Drivers/TrEEDxe/TpmDxe.inf
INF QcomPkg/Drivers/TrEEDxe/TrEEDxe.inf
INF QcomPkg/Drivers/QcomBds/QcomBds.inf
INF QcomPkg/Drivers/SerialDxe/SerialDxe.inf
INF QcomPkg/Drivers/AdapterInformationDxe/AdapterInformationDxe.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Drivers/DppDxe/DppDxe.inf
INF FmpDevicePkg/FmpDxe/78EF0A56-1CF0-4535-B5DA-F6FD2F405A25.inf
INF MdeModulePkg/Universal/EsrtDxe/EsrtDxe.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxe.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
    SECTION UI = "BDS_Menu.cfg"
    SECTION RAW = RawFiles/BDS_Menu.cfg
}

INF QcomPkg/QcomToolsPkg/WinDsdtUpdateControllerUI/WinDsdtUpdateControllerUI.inf

FILE FREEFORM = 96195F52-9EAA-436D-9A86-0FA02ACB39B0 {
    SECTION UI = "DriverList.cfg"
    SECTION RAW = RawFiles/DriverList.cfg
}


FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
    SECTION UI = "logo1.bmp"
    SECTION RAW = RawFiles/logo1.bmp
}


FILE FREEFORM = 8CAE2C55-FC5A-410B-812B-8CA22F572F36 {
    SECTION UI = "Panel_rm69299_amoled_fhd_plus_video.xml"
    SECTION RAW = RawFiles/Panel_rm69299_amoled_fhd_plus_video.xml
}


FILE FREEFORM = 8CAE2C55-FC5A-410B-812B-8CA22F557623 {
    SECTION UI = "Panel_rm69299_amoled_fhd_plus_cmd.xml"
    SECTION RAW = RawFiles/Panel_rm69299_amoled_fhd_plus_cmd.xml
}


FILE FREEFORM = 808D2786-42C3-4D03-A953-EAEEDBC85E66 {
    SECTION UI = "Panel_cls_proto_0_sn65dsi86_boe_fhd.xml"
    SECTION RAW = RawFiles/Panel_cls_proto_0_sn65dsi86_boe_fhd.xml
}


FILE FREEFORM = 314F53E7-7DAF-4FFC-B223-2C1137F5EE95 {
    SECTION UI = "Panel_cls_sn65dsi86_boe_fhd.xml"
    SECTION RAW = RawFiles/Panel_cls_sn65dsi86_boe_fhd.xml
}


FILE FREEFORM = 67651375-ED9F-4470-9710-009DB700A58D {
    SECTION UI = "7180_cls_external_dp_usb0.xml"
    SECTION RAW = RawFiles/7180_cls_external_dp_usb0.xml
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}


FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
    SECTION UI = "QcomChargerCfg.cfg"
    SECTION RAW = RawFiles/QcomChargerCfg.cfg
}

INF QcomPkg/Application/FastbootApp/FastbootApp.inf
INF EmbeddedPkg/Ebl/Ebl.inf
INF QcomPkg/QcomToolsPkg/UsbfnMsdApp/UsbfnMsdApp.inf
