INF QcomPkg/XBLCore/XBLCore.inf

FILE FREEFORM = DDE58710-41CD-4306-DBFB-3FA90BB1D2DD {
    SECTION UI = "uefiplat.cfg"
    SECTION RAW = RawFiles/uefiplat.cfg
}

INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
INF QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
INF QcomPkg/Drivers/ASN1X509Dxe/ASN1X509Dxe.inf
INF QcomPkg/Drivers/VerifiedBootDxe/VerifiedBootDxe.inf
INF QcomPkg/Drivers/TzDxe/ScmDxeLA.inf
INF QcomPkg/Drivers/TzDxe/TzDxeLA.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/RscRtDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/SCHandlerRtDxe.inf
INF QcomPkg/Drivers/VariableDxe/VariableDxe.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF QcomPkg/Drivers/FontDxe/FontDxe.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF QcomPkg/Drivers/QcomMpmTimerDxe/QcomMpmTimerDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF QcomPkg/Drivers/CmdDbDxe/CmdDbDxe.inf
INF QcomPkg/Drivers/RpmhDxe/RpmhDxe.inf
INF QcomPkg/Drivers/CPRDxe/CPRDxe.inf
INF QcomPkg/Drivers/PdcDxe/PdcDxe.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe.inf
INF QcomPkg/Drivers/UFSDxe/UFSDxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeLa.inf
INF QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
INF QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeLA.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
INF QcomPkg/Drivers/AdcDxe/AdcDxe.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/LimitsDxe/LimitsDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/vivoMemTestDxe/vivoMemTestDxe.inf
INF QcomPkg/Drivers/HashDxe/HashDxe.inf
INF QcomPkg/Drivers/CipherDxe/CipherDxe.inf
INF QcomPkg/Drivers/RNGDxe/RngDxe.inf
INF QcomPkg/Drivers/QcomBds/QcomBds.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Application/QcomChargerApp/QcomChargerApp.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxeLA.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
    SECTION UI = "BDS_Menu.cfg"
    SECTION RAW = RawFiles/BDS_Menu.cfg
}


FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
    SECTION UI = "logo1.bmp"
    SECTION RAW = RawFiles/logo1.bmp
}


FILE FREEFORM = 0926B060-FE13-4A95-A199-B90EBDD52BF9 {
    SECTION UI = "AnimationCfg.cfg"
    SECTION RAW = RawFiles/AnimationCfg.cfg
}


FILE FREEFORM = 15AA6AE1-94A3-4488-844C-1838240248AF {
    SECTION UI = "IQOO_FHD_19x5_9.bmp"
    SECTION RAW = RawFiles/IQOO_FHD_19x5_9.bmp
}


FILE FREEFORM = D6607463-AFD8-40FD-B939-69081630CA83 {
    SECTION UI = "IQOO_YD_FHD_19x5_9.bmp"
    SECTION RAW = RawFiles/IQOO_YD_FHD_19x5_9.bmp
}


FILE FREEFORM = E13009E1-EA10-4541-9563-6AD4C20638DE {
    SECTION UI = "IQOO4G_FHD_19x5_9.bmp"
    SECTION RAW = RawFiles/IQOO4G_FHD_19x5_9.bmp
}


FILE FREEFORM = D78EE927-32D1-4972-B721-DA73D7BBB629 {
    SECTION UI = "IQOO4G_YD_FHD_19x5_9.bmp"
    SECTION RAW = RawFiles/IQOO4G_YD_FHD_19x5_9.bmp
}


FILE FREEFORM = 3584A8C2-4CD9-4621-A676-4263A97CBA21 {
    SECTION UI = "lowpower_logo1.bmp"
    SECTION RAW = RawFiles/lowpower_logo1.bmp
}


FILE FREEFORM = 69FD64F2-7139-4DCB-B301-D05801B2E448 {
    SECTION UI = "lowpower_logo2.bmp"
    SECTION RAW = RawFiles/lowpower_logo2.bmp
}


FILE FREEFORM = 9FE3EB16-5E37-495C-BA37-60EFF3204271 {
    SECTION UI = "lowpower_logo3.bmp"
    SECTION RAW = RawFiles/lowpower_logo3.bmp
}


FILE FREEFORM = FC33FCAD-A252-4535-9A06-E977FA6E8662 {
    SECTION UI = "poweroff_chg_logo.bmp"
    SECTION RAW = RawFiles/poweroff_chg_logo.bmp
}


FILE FREEFORM = 8CAE2C55-FC5A-410B-812B-8CA22F572F36 {
    SECTION UI = "Panel_truly_wqxga_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dsc_cmd.xml
}


FILE FREEFORM = 13AC9DC9-0092-4374-AE1A-06FF35950FD0 {
    SECTION UI = "Panel_truly_wqxga_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dsc_vid.xml
}


FILE FREEFORM = FC6315F9-F8FE-4222-A1E3-226DF55D7592 {
    SECTION UI = "Panel_truly_wqxga_dual_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dual_cmd.xml
}


FILE FREEFORM = 95E7B040-26A2-4511-9ABB-1D95D6DA7082 {
    SECTION UI = "Panel_truly_wqxga_dual_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dual_vid.xml
}


FILE FREEFORM = 8BC595B7-391A-4A9A-8256-5B9983B30392 {
    SECTION UI = "Panel_sharp_4k_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_sharp_4k_dsc_cmd.xml
}


FILE FREEFORM = 19B58ACD-B1F8-4078-B9A5-A33584B680E2 {
    SECTION UI = "Panel_sharp_4k_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sharp_4k_dsc_vid.xml
}


FILE FREEFORM = 0AE323D6-2EBE-11E8-8349-9BA636A0D80C {
    SECTION UI = "Panel_sharp_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_sharp_1080p_cmd.xml
}


FILE FREEFORM = 87273B42-311D-11E8-9324-DFB2DADFC3D1 {
    SECTION UI = "Panel_truly_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_1080p_cmd.xml
}


FILE FREEFORM = BAFD3200-311D-11E8-8651-0FB3CACF38FB {
    SECTION UI = "Panel_truly_1080p_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_1080p_vid.xml
}


FILE FREEFORM = 88CA5ABF-D0AC-4093-A68C-0CFAE1EF9635 {
    SECTION UI = "Panel_boe_amoled_wqhd_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wqhd_dsc_cmd.xml
}


FILE FREEFORM = 45A8FDA2-4FAD-4234-BCDA-D1778611CE13 {
    SECTION UI = "Panel_boe_amoled_wqhd_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wqhd_dsc_vid.xml
}


FILE FREEFORM = 2BCA3B86-E175-4609-AC7F-207908B89C75 {
    SECTION UI = "Panel_primary_sharp_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_primary_sharp_1080p_cmd.xml
}


FILE FREEFORM = A3607731-F28D-496C-83D3-FB182F885F8C {
    SECTION UI = "Panel_secondary_truly_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_secondary_truly_1080p_cmd.xml
}


FILE FREEFORM = 32C7620B-9746-4BB6-8166-605682A2C58A {
    SECTION UI = "Panel_nt36850_truly_wqhd_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt36850_truly_wqhd_cmd.xml
}


FILE FREEFORM = 2FD70D55-C89A-47C8-A960-5A3AAA10426C {
    SECTION UI = "Panel_sdx55_truly_wqxga_dual_cmd.xml"
    SECTION RAW = RawFiles/Panel_sdx55_truly_wqxga_dual_cmd.xml
}


FILE FREEFORM = 13E35E77-F1E0-4639-9021-70CBA62FB897 {
    SECTION UI = "Panel_sdx55_truly_wqxga_dual_vid.xml"
    SECTION RAW = RawFiles/Panel_sdx55_truly_wqxga_dual_vid.xml
}


FILE FREEFORM = 07777D7D-677F-47F4-A1FB-3BB1E08E607A {
    SECTION UI = "Panel_sdx55_sharp_4k_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_sdx55_sharp_4k_dsc_cmd.xml
}


FILE FREEFORM = 151F4DFB-643B-418D-ACB3-A66BC8D7A4EF {
    SECTION UI = "Panel_sdx55_sharp_4k_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sdx55_sharp_4k_dsc_vid.xml
}


FILE FREEFORM = B64AF9F4-2636-4EB8-B55B-F5362338B3C2 {
    SECTION UI = "Panel_pd1824_samsung_sofeg04_cmd.xml"
    SECTION RAW = RawFiles/Panel_pd1824_samsung_sofeg04_cmd.xml
}


FILE FREEFORM = D3BB285E-14DC-496B-8F6F-2C33970023E6 {
    SECTION UI = "Panel_pd1916_samsung_sofeg04_cmd.xml"
    SECTION RAW = RawFiles/Panel_pd1916_samsung_sofeg04_cmd.xml
}


FILE FREEFORM = 2E2D4747-9F26-4788-A4CA-C0B68CCF2768 {
    SECTION UI = "Panel_pd1936_samsung_sofeg04_cmd.xml"
    SECTION RAW = RawFiles/Panel_pd1936_samsung_sofeg04_cmd.xml
}


FILE FREEFORM = 8E0D637E-DC20-471F-AE62-62F78931A3BF {
    SECTION UI = "Panel_pd1923_samsung_fhd_plus_sofego4_cmd.xml"
    SECTION RAW = RawFiles/Panel_pd1923_samsung_fhd_plus_sofego4_cmd.xml
}


FILE FREEFORM = 3E5584ED-05D4-4267-9048-0D47F76F4248 {
    SECTION UI = "battery_symbol_Soc10.bmp"
    SECTION RAW = RawFiles/battery_symbol_Soc10.bmp
}


FILE FREEFORM = 4753E815-DDD8-402D-BF69-9B8C4EB7573E {
    SECTION UI = "battery_symbol_NoBattery.bmp"
    SECTION RAW = RawFiles/battery_symbol_NoBattery.bmp
}


FILE FREEFORM = 03DED53E-BECD-428F-9F79-5ABA64C58445 {
    SECTION UI = "battery_symbol_Nocharger.bmp"
    SECTION RAW = RawFiles/battery_symbol_Nocharger.bmp
}


FILE FREEFORM = 8B86CD38-C772-4FCF-85AA-345B2B3C1AB4 {
    SECTION UI = "battery_symbol_LowBatteryCharging.bmp"
    SECTION RAW = RawFiles/battery_symbol_LowBatteryCharging.bmp
}


FILE FREEFORM = 3FD97907-93F1-4349-AF3C-3B68B0A5E626 {
    SECTION UI = "battery_symbol_LowBattery.bmp"
    SECTION RAW = RawFiles/battery_symbol_LowBattery.bmp
}


FILE FREEFORM = E2EA5A4F-98BD-4203-AB49-399505DDFB7D {
    SECTION UI = "tsens_thermal_symbol.bmp"
    SECTION RAW = RawFiles/tsens_thermal_symbol.bmp
}


FILE FREEFORM = C72FB1A9-5527-4E13-BAC4-F671D0330145 {
    SECTION UI = "tsens_thermal_err_symbol.bmp"
    SECTION RAW = RawFiles/tsens_thermal_err_symbol.bmp
}


FILE FREEFORM = B0F8D1BE-5353-4812-B1F6-07E7768204CC {
    SECTION UI = "battery_symbol_DebugBoot.bmp"
    SECTION RAW = RawFiles/battery_symbol_DebugBoot.bmp
}


FILE FREEFORM = F9E8F683-E065-4E09-B4F9-0230D7CECD08 {
    SECTION UI = "battery_symbol_DebugStay.bmp"
    SECTION RAW = RawFiles/battery_symbol_DebugStay.bmp
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}


FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
    SECTION UI = "QcomChargerCfg.cfg"
    SECTION RAW = RawFiles/QcomChargerCfg.cfg
}


FILE FREEFORM = F780C779-DD7C-47CD-BD1A-5EB414C51704 {
    SECTION UI = "BATTERY.PROVISION"
    SECTION RAW = RawFiles/BATTERY.PROVISION
}

INF QcomPkg/Drivers/vivoHardwareVersion/vivoHardwareVersionDxe.inf
